export type CancelReason =
  | 'INSUFFICIENT_STOCK'
  | 'INVENTORY_UNREACHABLE'
  | 'RESERVATION_INCOMPLETE'
  | 'PAYMENT_DECLINED'
  | 'PAYMENT_TIMEOUT'
  | 'DEAL_FAILED'
  | 'DEAL_RESOLVED'
  | 'PARTICIPANT_LEFT'
  | 'SERVER_ERROR';
