export enum OrderStatusFiltration {
  PENDING_PAYMENT = 'PENDING_PAYMENT', // PENDING_CHARGE/AUTHORIZATION/CAPTURE/VOID
  PENDING_DELIVERY = 'PENDING_DELIVERY', // SHIPPING + PROCESSING
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

